/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package est.ups.edu.ec.cedilloe_millerm_final.view;

import est.ups.edu.ec.cedilloe_millerm_final.controller.ChangeOpenDoorTimeController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Mateo
 */
public class ChangeOpenDoorTimeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangeOpenDoorTimeView.class.getName());
    private ChangeOpenDoorTimeController controller;
    /**
     * Creates new form ChangeOpenDoorTimeView
     */
    public ChangeOpenDoorTimeView() {
        initComponents();
        controller = new ChangeOpenDoorTimeController(this);
        setSpinnerDefaultValues();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbxUnitTime = new javax.swing.JComboBox<>();
        spnTime = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtActTime = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxUnitTimeDoor = new javax.swing.JComboBox<>();
        spnTimeDoor = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtActTimeDoor = new javax.swing.JTextField();
        btnCancelDoor = new javax.swing.JButton();
        btnChangeDoor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("New Time:");

        cbxUnitTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seg", "min", "hr", "day" }));

        jLabel3.setText("Actual Time:");

        txtActTime.setEditable(false);
        txtActTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnCancel.setText("Cancel");

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Waiting Time Panel");

        jLabel4.setText("Unit of time: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel5.setText("New Time:");

        cbxUnitTimeDoor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seg", "min", "hr", "day" }));

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel6.setText("Actual Time:");

        txtActTimeDoor.setEditable(false);
        txtActTimeDoor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnCancelDoor.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelDoor.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btnCancelDoor.setText("Cancel");
        btnCancelDoor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnChangeDoor.setBackground(new java.awt.Color(237, 237, 206));
        btnChangeDoor.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btnChangeDoor.setText("Change");
        btnChangeDoor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChangeDoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDoorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Change Waiting Time Panel");

        jLabel8.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel8.setText("Unit of time: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnChangeDoor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelDoor, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxUnitTimeDoor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnTimeDoor)
                            .addComponent(txtActTimeDoor))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActTimeDoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTimeDoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbxUnitTimeDoor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChangeDoor)
                    .addComponent(btnCancelDoor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnChangeDoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDoorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeDoorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelDoor;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChangeDoor;
    private javax.swing.JComboBox<String> cbxUnitTime;
    private javax.swing.JComboBox<String> cbxUnitTimeDoor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner spnTime;
    private javax.swing.JSpinner spnTimeDoor;
    private javax.swing.JTextField txtActTime;
    private javax.swing.JTextField txtActTimeDoor;
    // End of variables declaration//GEN-END:variables
    
    public void setSpinnerDefaultValues() {

        SpinnerNumberModel model = new SpinnerNumberModel(
                1,    // valor inicial
                1,    // mínimo
                60,   // máximo
                1     // incremento
        );

        spnTimeDoor.setModel(model);
    }

    public ChangeOpenDoorTimeController getController() {
        return controller;
    }

    public void setController(ChangeOpenDoorTimeController controller) {
        this.controller = controller;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnCancelDoor() {
        return btnCancelDoor;
    }

    public void setBtnCancelDoor(JButton btnCancelDoor) {
        this.btnCancelDoor = btnCancelDoor;
    }

    public JButton getBtnChange() {
        return btnChange;
    }

    public void setBtnChange(JButton btnChange) {
        this.btnChange = btnChange;
    }

    public JButton getBtnChangeDoor() {
        return btnChangeDoor;
    }

    public void setBtnChangeDoor(JButton btnChangeDoor) {
        this.btnChangeDoor = btnChangeDoor;
    }

    public JComboBox<String> getCbxUnitTime() {
        return cbxUnitTime;
    }

    public void setCbxUnitTime(JComboBox<String> cbxUnitTime) {
        this.cbxUnitTime = cbxUnitTime;
    }

    public JComboBox<String> getCbxUnitTimeDoor() {
        return cbxUnitTimeDoor;
    }

    public void setCbxUnitTimeDoor(JComboBox<String> cbxUnitTimeDoor) {
        this.cbxUnitTimeDoor = cbxUnitTimeDoor;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JSpinner getSpnTime() {
        return spnTime;
    }

    public void setSpnTime(JSpinner spnTime) {
        this.spnTime = spnTime;
    }

    public JSpinner getSpnTimeDoor() {
        return spnTimeDoor;
    }

    public void setSpnTimeDoor(JSpinner spnTimeDoor) {
        this.spnTimeDoor = spnTimeDoor;
    }

    public JTextField getTxtActTime() {
        return txtActTime;
    }

    public void setTxtActTime(JTextField txtActTime) {
        this.txtActTime = txtActTime;
    }

    public JTextField getTxtActTimeDoor() {
        return txtActTimeDoor;
    }

    public void setTxtActTimeDoor(JTextField txtActTimeDoor) {
        this.txtActTimeDoor = txtActTimeDoor;
    }
    
    
    
}
