/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package est.ups.edu.ec.cedilloe_millerm_final.view;

import est.ups.edu.ec.cedilloe_millerm_final.controller.MenuController;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Mateo
 */
public class MenuView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuView.class.getName());
    private MenuController controller;
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setLocationRelativeTo(null);
        controller = new MenuController(this);
        this.getContentPane().setBackground(new Color(84, 119, 146));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        btnReadUsers = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnChangeWaitingTime = new javax.swing.JButton();
        btnChangeAttempts = new javax.swing.JButton();
        btnViewLogs = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        lblLogs = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnChangeDoorTime = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(98, 159, 173));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Menu Panel");

        btnReadUsers.setBackground(new java.awt.Color(237, 237, 206));
        btnReadUsers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnReadUsers.setText("Read");

        btnCreateUser.setBackground(new java.awt.Color(237, 237, 206));
        btnCreateUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCreateUser.setText("Create ");

        btnUpdateUser.setBackground(new java.awt.Color(237, 237, 206));
        btnUpdateUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnUpdateUser.setText("Update");

        btnDeleteUser.setBackground(new java.awt.Color(237, 237, 206));
        btnDeleteUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnDeleteUser.setText("Delete");

        btnChangeWaitingTime.setBackground(new java.awt.Color(237, 237, 206));
        btnChangeWaitingTime.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnChangeWaitingTime.setText("Change Waiting Time");

        btnChangeAttempts.setBackground(new java.awt.Color(237, 237, 206));
        btnChangeAttempts.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnChangeAttempts.setText("Change Attempts");

        btnViewLogs.setBackground(new java.awt.Color(237, 237, 206));
        btnViewLogs.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnViewLogs.setText("View Logs");

        lblUser.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User");

        lblSettings.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setText("General Settings");

        lblLogs.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblLogs.setForeground(new java.awt.Color(255, 255, 255));
        lblLogs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogs.setText("Logs");

        btnLogOut.setBackground(new java.awt.Color(248, 116, 116));
        btnLogOut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnChangeDoorTime.setBackground(new java.awt.Color(237, 237, 206));
        btnChangeDoorTime.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnChangeDoorTime.setText("Change Open Door Time");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReadUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangeWaitingTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeAttempts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeDoorTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(btnViewLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReadUsers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSettings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangeWaitingTime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangeAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnViewLogs)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChangeDoorTime)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeAttempts;
    private javax.swing.JButton btnChangeDoorTime;
    private javax.swing.JButton btnChangeWaitingTime;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReadUsers;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnViewLogs;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblLogs;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnChangeAttempts() {
        return btnChangeAttempts;
    }

    public void setBtnChangeAttempts(JButton btnChangeAttempts) {
        this.btnChangeAttempts = btnChangeAttempts;
    }

    public JButton getBtnChangeWaitingTime() {
        return btnChangeWaitingTime;
    }

    public void setBtnChangeWaitingTime(JButton btnChangeWaitingTime) {
        this.btnChangeWaitingTime = btnChangeWaitingTime;
    }

    public JButton getBtnCreateUser() {
        return btnCreateUser;
    }

    public void setBtnCreateUser(JButton btnCreateUser) {
        this.btnCreateUser = btnCreateUser;
    }

    public JButton getBtnDeleteUser() {
        return btnDeleteUser;
    }

    public void setBtnDeleteUser(JButton btnDeleteUser) {
        this.btnDeleteUser = btnDeleteUser;
    }

    public JButton getBtnReadUsers() {
        return btnReadUsers;
    }

    public void setBtnReadUsers(JButton btnReadUsers) {
        this.btnReadUsers = btnReadUsers;
    }

    public JButton getBtnUpdateUser() {
        return btnUpdateUser;
    }

    public void setBtnUpdateUser(JButton btnUpdateUser) {
        this.btnUpdateUser = btnUpdateUser;
    }

    public JButton getBtnViewLogs() {
        return btnViewLogs;
    }

    public void setBtnViewLogs(JButton btnViewLogs) {
        this.btnViewLogs = btnViewLogs;
    }

    public JLabel getLblLogs() {
        return lblLogs;
    }

    public void setLblLogs(JLabel lblLogs) {
        this.lblLogs = lblLogs;
    }

    public JLabel getLblSettings() {
        return lblSettings;
    }

    public void setLblSettings(JLabel lblSettings) {
        this.lblSettings = lblSettings;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public void setBtnLogOut(JButton btnLogOut) {
        this.btnLogOut = btnLogOut;
    }

    public MenuController getController() {
        return controller;
    }

    public void setController(MenuController controller) {
        this.controller = controller;
    }

    public JButton getBtnChangeDoorTime() {
        return btnChangeDoorTime;
    }

    public void setBtnChangeDoorTime(JButton btnChangeDoorTime) {
        this.btnChangeDoorTime = btnChangeDoorTime;
    }
    
    
    
    
    
    
}
