/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package est.ups.edu.ec.cedilloe_millerm_final.view;

import com.toedter.calendar.JDateChooser;
import est.ups.edu.ec.cedilloe_millerm_final.controller.ReadLogsController;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Mateo
 */
public class ReadLogsView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReadLogsView.class.getName());
    private ReadLogsController controller;
    
    Calendar date_start = new GregorianCalendar();
    Calendar date_end = new GregorianCalendar();
    
    /**
     * Creates new form ReadLogsView
     */
    public ReadLogsView() {
        initComponents();
        setLocationRelativeTo(null);
        controller = new ReadLogsController(this);

        jdDate_start.setCalendar(date_start);
        jdDate_end.setCalendar(date_end);

        tblLogs.setPreferredSize(null);

        tblLogs.setFillsViewportHeight(true);
        jScrollPane2.setVerticalScrollBarPolicy(
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED
        );
        this.getContentPane().setBackground(new Color(84, 119, 146));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        jdDate_start = new com.toedter.calendar.JDateChooser();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        jdDate_end = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();
        btnGrafica = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Logs ");

        btnGoBack.setBackground(new java.awt.Color(237, 237, 206));
        btnGoBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(102, 102, 0));
        btnGoBack.setText("Go Back");
        btnGoBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jdDate_start.setDateFormatString("dd-MM-yyyy HH:mm:ss");

        lblStart.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblStart.setForeground(new java.awt.Color(255, 255, 255));
        lblStart.setText("Start");

        lblEnd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(255, 255, 255));
        lblEnd.setText("End");

        jdDate_end.setDateFormatString("dd-MM-yyyy HH:mm:ss");

        btnSearch.setBackground(new java.awt.Color(215, 240, 250));
        btnSearch.setForeground(new java.awt.Color(0, 0, 255));
        btnSearch.setText("🔍");
        btnSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblLogs.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ID usuario", "Fecha", "Acceso"
            }
        ));
        tblLogs.setToolTipText("");
        tblLogs.setPreferredSize(new java.awt.Dimension(400, 100));
        jScrollPane2.setViewportView(tblLogs);

        btnGrafica.setBackground(new java.awt.Color(204, 255, 204));
        btnGrafica.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGrafica.setForeground(new java.awt.Color(0, 102, 0));
        btnGrafica.setText("Graphic");
        btnGrafica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdDate_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdDate_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 218, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdDate_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnd)
                                .addGap(7, 7, 7)
                                .addComponent(jdDate_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdDate_end;
    private com.toedter.calendar.JDateChooser jdDate_start;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblLogs;
    // End of variables declaration//GEN-END:variables
    

    public ReadLogsController getController() {
        return controller;
    }

    public void setController(ReadLogsController controller) {
        this.controller = controller;
    }

    public JButton getBtnGoBack() {
        return btnGoBack;
    }

    public void setBtnGoBack(JButton btnGoBack) {
        this.btnGoBack = btnGoBack;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public JTable getTblLogs() {
        return tblLogs;
    }

    public void setTblLogs(JTable tblLogs) {
        this.tblLogs = tblLogs;
    }

    public Calendar getDate_start() {
        return date_start;
    }

    public void setDate_start(Calendar date_start) {
        this.date_start = date_start;
    }

    public Calendar getDate_end() {
        return date_end;
    }

    public void setDate_end(Calendar date_end) {
        this.date_end = date_end;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public void setBtnSearch(JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    public JDateChooser getJdDate_end() {
        return jdDate_end;
    }

    public void setJdDate_end(JDateChooser jdDate_end) {
        this.jdDate_end = jdDate_end;
    }

    public JDateChooser getJdDate_start() {
        return jdDate_start;
    }

    public void setJdDate_start(JDateChooser jdDate_start) {
        this.jdDate_start = jdDate_start;
    }

    public JLabel getLblEnd() {
        return lblEnd;
    }

    public void setLblEnd(JLabel lblEnd) {
        this.lblEnd = lblEnd;
    }

    public JLabel getLblStart() {
        return lblStart;
    }

    public void setLblStart(JLabel lblStart) {
        this.lblStart = lblStart;
    }

    public JButton getBtnGrafica() {
        return btnGrafica;
    }

    public void setBtnGrafica(JButton btnGrafica) {
        this.btnGrafica = btnGrafica;
    }
}
